CREATE TABLE STUDENT(
	S_NO INT PRIMARY KEY AUTO_INCREMENT,
	S_ID VARCHAR(20) NOT NULL, 
	S_NAME VARCHAR(20) NOT NULL, 
	S_BIRTH DATE NOT NULL, 
	S_GENDER BOOLEAN NOT NULL, 
	S_SCHOOL VARCHAR(20) NOT NULL, 
	S_GRADE INT NOT NULL,
	S_CLASS INT NOT NULL,
	S_PASSWORD VARCHAR(100) NOT NULL, 
	S_EMAIL VARCHAR(20) UNIQUE KEY NOT NULL
);

CREATE TABLE TEACHER(
	T_NO INT PRIMARY KEY AUTO_INCREMENT,
	T_ID VARCHAR(20) NOT NULL,
	T_NAME VARCHAR(20) NOT NULL,
	T_BIRTH DATE NOT NULL,
	T_GENDER BOOLEAN NOT NULL,
	T_SCHOOL VARCHAR(20) NOT NULL,
	T_PASSWORD VARCHAR(100) NOT NULL,
	T_EMAIL VARCHAR(20) UNIQUE KEY NOT NULL
);

CREATE TABLE CLASS(
	C_NO INT PRIMARY KEY AUTO_INCREMENT,
	C_NAME VARCHAR(20) NOT NULL,
	C_TIME VARCHAR(20) NOT NULL,
	C_STUNUM INT NOT NULL,
	T_NO INT NOT NULL,
	FOREIGN KEY(T_NO) REFERENCES TEACHER(T_NO) ON DELETE 
	CASCADE ON UPDATE CASCADE
);

CREATE TABLE REGISTER(
	R_NO INT PRIMARY KEY AUTO_INCREMENT,
	C_NO INT NOT NULL, 
	S_NO INT NOT NULL,
	R_TIME DATETIME NOT NULL DEFAULT NOW(),
	FOREIGN KEY(C_NO) REFERENCES CLASS(C_NO) ON DELETE CASCADE ON UPDATE CASCADE, 
	FOREIGN KEY(S_NO) REFERENCES STUDENT(S_NO) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE QUIZ(
	Q_NO INT PRIMARY KEY AUTO_INCREMENT,
	C_NO INT NOT NULL,
	Q_QUES VARCHAR(200) NOT NULL,
	Q_ANS VARCHAR(200) NOT NULL DEFAULT '답 없음.',
	Q_TYPE BOOLEAN NOT NULL,
	Q_TIMELIMIT TIME NOT NULL,
	FOREIGN KEY(C_NO) REFERENCES CLASS(C_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE QUIZCHECK(
	QC_NO INT PRIMARY KEY AUTO_INCREMENT,
	Q_NO INT NOT NULL,
	S_NO INT NOT NULL,
 	QC_STATE BOOLEAN NOT NULL DEFAULT FALSE,
	QC_TIME DATETIME NOT NULL DEFAULT NOW(),
	QC_ANS VARCHAR(200) NOT NULL DEFAULT '답 없음.',
	FOREIGN KEY(Q_NO) REFERENCES QUIZ(Q_NO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(S_NO) REFERENCES STUDENT(S_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ATTEND(
	A_NO INT PRIMARY KEY AUTO_INCREMENT,
	S_NO INT NOT NULL,
	C_NO INT NOT NULL,
	A_STATE INT NOT NULL DEFAULT 2,
	A_STARTTIME DATETIME NOT NULL DEFAULT NOW(),
	A_TIME DATETIME NOT NULL DEFAULT NOW(),
	FOREIGN KEY(C_NO) REFERENCES CLASS(C_NO) ON DELETE CASCADE ON UPDATE CASCADE, 
	FOREIGN KEY(S_NO) REFERENCES STUDENT(S_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MSGROOM(
    ROOMID VARCHAR(10) PRIMARY KEY
);